### ISSUE TITLE
Package zendframework/zend-diactoros should be replaced

### ISSUE THREAD

**Issue by Fantom409** [n1215/roadrunner-docker-skeleton#8]
When I install composer packages I see warning: 
"Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead."

**Comment by n1215** [comment]
zendframework/zend-diactoros is [a RoadRunner's dependency](https://github.com/spiral/roadrunner/blob/v1.6.2/composer.json#L22).
This repository depends on nyholm/psr7 instead of diactoros.

The dependency on the concrete PSR-7 package is planned to be removed in RoadRunner 2.0.
see: https://github.com/spiral/roadrunner/issues/230
